#include <stdio.h>

int main() {
    // Generate a document and write it to standard output
    printf("This is a sample document generated by gendoc.\n");
    printf("You can customize this document as needed.\n");
    return 0;
}